name: presence
version: 1.0.0+1
publish_to: none
description: A presence app built with flutter
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  email_validator: 2.1.17
  http: 0.13.5
  network_info_plus: 3.0.4
  flutter: 
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  firebase_database: ^10.2.2
  uuid: ^3.0.7
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  dio: ^5.2.1+1

dev_dependencies: 
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/launcher_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/launcher_icon_256x256.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/launcher_icon.png"
